modkey = "Mod4"
mousekey = "Mod4"
# workspaces = [
#     { x = 0, y = 0, width = 1920, height = 1080 },
#     { x = 0, y = 1920, width = 3440, height = 1440 },
# ]
workspaces = []
tags = ["1", "2", "3", "4"]
layouts = ["MainAndVertStack", "Monocle"]
layout_mode = "Workspace"
scratchpad = []
disable_current_tag_swap = false
focus_behaviour = "ClickTo"
focus_new_windows = true

keybind = [
    { modifier = ["modkey"], key = "p", command = "Execute", value = "dmenu_run" },
    # { modifier = ["modkey"], key = "p", command = "Execute", value = "synapse" },
    # { modifier = ["Control"], key = "Space", command = "Execute", value = "dmenu_run" },
    { modifier = ["modkey", "Shift"], key = "Return", command = "Execute", value = "alacritty" },
    { modifier = ["modkey", "Control"], key = "q", command = "CloseWindow" },
    { modifier = ["modkey", "Alt", "Shift"], key = "r", command = "HardReload" },
    { modifier = ["modkey", "Shift"], key = "r", command = "SoftReload" },
    { modifier = ["modkey", "Shift"], key = "x", command = "Execute", value = "loginctl kill-session $XDG_SESSION_ID" },
    { modifier = ["modkey", "Control"], key = "l", command = "Execute", value = "slock" },
    { modifier = ["modkey"], key = "w", command = "SwapTags" },
    { modifier = ["modkey", "Alt"], key = "h", command = "MoveWindowUp" },
    { modifier = ["modkey", "Alt"], key = "l", command = "MoveWindowDown" },
    { modifier = ["modkey"], key = "Return", command = "MoveWindowTop" },
    { modifier = ["modkey"], key = "h", command = "FocusWindowUp" },
    { modifier = ["modkey"], key = "l", command = "FocusWindowDown" },
    { modifier = ["modkey", "Shift"], key = "l", command = "IncreaseMainWidth", value = "3" },
    { modifier = ["modkey", "Shift"], key = "h", command = "DecreaseMainWidth", value = "3" },
    { modifier = ["modkey"], key = "backslash", command = "NextLayout" },
    { modifier = ["modkey"], key = "t", command = "SetLayout", value = "MainAndVertStack" },
    { modifier = ["modkey"], key = "m", command = "SetLayout", value = "Monocle" },
    { modifier = ["modkey"], key = "f", command = "ToggleFloating" },
    { modifier = ["Alt"], key = "l", command = "FocusNextTag" },
    { modifier = ["Alt"], key = "h", command = "FocusPreviousTag" },
    { modifier = ["modkey"], key = "Right", command = "FocusNextTag" },
    { modifier = ["modkey"], key = "Left", command = "FocusPreviousTag" },
    { modifier = ["Control"], key = "Tab", command = "ReturnToLastTag" },
    { modifier = ["modkey"], key = "1", command = "GotoTag", value = "1" },
    { modifier = ["modkey"], key = "2", command = "GotoTag", value = "2" },
    { modifier = ["modkey"], key = "3", command = "GotoTag", value = "3" },
    { modifier = ["modkey"], key = "4", command = "GotoTag", value = "4" },
    { modifier = ["modkey"], key = "5", command = "GotoTag", value = "5" },
    { modifier = ["modkey"], key = "6", command = "GotoTag", value = "6" },
    { modifier = ["modkey"], key = "7", command = "GotoTag", value = "7" },
    { modifier = ["modkey"], key = "8", command = "GotoTag", value = "8" },
    { modifier = ["modkey"], key = "9", command = "GotoTag", value = "9" },
    { modifier = ["modkey", "Shift"], key = "1", command = "MoveToTag", value = "1" },
    { modifier = ["modkey", "Shift"], key = "2", command = "MoveToTag", value = "2" },
    { modifier = ["modkey", "Shift"], key = "3", command = "MoveToTag", value = "3" },
    { modifier = ["modkey", "Shift"], key = "4", command = "MoveToTag", value = "4" },
    { modifier = ["modkey", "Shift"], key = "5", command = "MoveToTag", value = "5" },
    { modifier = ["modkey", "Shift"], key = "6", command = "MoveToTag", value = "6" },
    { modifier = ["modkey", "Shift"], key = "7", command = "MoveToTag", value = "7" },
    { modifier = ["modkey", "Shift"], key = "8", command = "MoveToTag", value = "8" },
    { modifier = ["modkey", "Shift"], key = "9", command = "MoveToTag", value = "9" },
]
