#!/bin/bash

xrandr > /home/mike/xrandr_config

wallpaper="$HOME/Pictures/Wallpapers/City3_GIMP_Denoise.jpg"
wallpaper_small="$HOME/Pictures/Wallpapers/City3_small.jpg"

# set key repeat rate
xset r rate 250 30

if xrandr --current | grep "DP-1-0 connected"; then
    feh --bg-center "$wallpaper"
elif xrandr --current | grep "DP-1-4 connected"; then
    feh --bg-center "$wallpaper"
elif xrandr --current | grep "DP-0 connected primary"; then
    feh --bg-center "$wallpaper"
elif xrandr --current | grep "DP-4 connected primary"; then
    feh --bg-center "$wallpaper"
else
    feh --bg-center "$wallpaper_small"
fi

# launch fusuma if it isn't already running
if ! pgrep fusuma; then
    fusuma -d
fi

# set up screen locker
xset s 300 300 # Dim screen after 300 seconds, lock screen after 300 more
xset dpms 605  # Turn off screen after 605 seconds
if pgrep xss-lock; then
    pkill xss-lock
fi
xss-lock -n /home/mike/scripts/dim-screen.sh -- i3lock-fancy -n

# launch auto disk mounter
if ! pgrep udiskie; then
    udiskie &
fi

# ensure bluetooth is powered
bluetoothctl power on

# start Nextcloud daemon
if ! pgrep nextcloud; then
    nextcloud --background &
fi

# start xflux
if ! pgrep xflux; then
    xflux -z 92508
fi

# start clipmenud
if ! pgrep -f /usr/bin/clipmenud; then
    CM_SELECTIONS=clipboard clipmenud &
fi

# setup autorandr
udev_rules_dir="$(pkg-config --variable=udevdir udev)/rules.d"
udev_rule="$udev_rules_dir/40-monitor-hotplug.rules"
echo 'ACTION=="change", SUBSYSTEM=="drm", RUN+="/usr/bin/autorandr --batch --change --default default"' |
    sudo tee "$udev_rule"

