#!/bin/bash

brightness_file="/tmp/brightness"

function dim_screen() {
    echo "$(xbacklight -get)" > $brightness_file
    xbacklight -set 5 -time 500 -fps 30
}

function restore_screen() {
    if [ -e $brightness_file ]; then
        brightness="$(cat $brightness_file)"
    else
        brightness=80
    fi
    xbacklight -set $brightness
    rm $brightness_file
}


while getopts "drs0" opt; do
    case $opt in
      d)
          dim_screen
	;;
      r)
          restore_screen
	;;
        *)
	exit 1
	;;
    esac
done
