#!/bin/bash

set -e

udev_rules_dir="$(pkg-config --variable=udevdir udev)/rules.d"
udev_rule="$udev_rules_dir/40-monitor-hotplug.rules"

remove_udev_rule() {
    sudo rm -f "$udev_rule"
}

reinstall_udev_rule() {
    sudo echo 'ACTION=="change", SUBSYSTEM=="drm", RUN+="/usr/bin/autorandr --batch --change --default default"' >"$udev_rule"
}

main() {
    remove_udev_rule
    trap reinstall_udev_rule EXIT
    echo -ne "autorandr has been paused, press Enter to resume it..."
    read -r
}

main "$@"
