theme = "onedark"

[editor]
scrolloff = 1
line-number = "relative"
true-color = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.lsp]
display-messages = true

[keys.normal]
"C-j" = "scroll_down"
"C-k" = "scroll_up"
"[" = { g = "goto_prev_diag"}
"]" = { g = "goto_next_diag"}
"G" = "goto_file_end"
"0" = "goto_line_start"
"$" = "goto_line_end"
"_" = "goto_first_nonwhitespace"
"D" = "kill_to_line_end"
"V" = ["select_mode", "extend_to_line_bounds"]
"C-v" = ["copy_selection_on_next_line"]
"%" = "match_brackets"
esc = ["collapse_selection", "keep_primary_selection"]
w = ["move_next_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]

[keys.insert]
"C-j" = "scroll_down"
"C-k" = "scroll_up"
esc = ["collapse_selection", "normal_mode"]

[keys.select]
"C-j" = "scroll_down"
"C-k" = "scroll_up"
K = ["extend_line_up", "extend_to_line_bounds"]
J = ["extend_line_down", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"G" = "goto_file_end"
