# [language-server.rust-analyzer.config.check]
# command = "clippy"

# [[language]]
# name = "rust"

# [language.auto-pairs]
# '(' = ')'
# '{' = '}'
# '[' = ']'
# '"' = '"'
# "'" = "'"
# '`' = '`'
# '<' = '>'

# [[language]]
# name = "python"
# scope = "source.python"
# injection-regex = "python"
# file-types = ["py"]
# shebangs = ["python"]
# roots = []
# comment-token = "#"
# # language-server = { command = "pyright-langserver", args = ["--stdio"] }
# indent = { tab-width = 4, unit = "    " }
